name: Construcción infraestructura en Azure

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  Deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login en Azure
        run: | 
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
      
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Inicializar Terraform
        id: init
        run: cd infra && terraform init
      
      - name: Validar Terraform
        id: validate
        run: cd infra && terraform validate -no-color
      
      - name: Importar recursos existentes en Azure
        run: |
          cd infra
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/upt-proyecto-valverde-lizarrag || true
          terraform import azurerm_linux_web_app.webapp /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/upt-proyecto-valverde-lizarrag/providers/Microsoft.Web/sites/upt-proyecto-valverde-lizarrag || true
          terraform import azurerm_dns_zone.dns /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/upt-proyecto-valverde-lizarrag/providers/Microsoft.Network/dnsZones/valverdelizarraga.azurewebsites.net || true
      
      - name: Planificar Terraform
        run: cd infra && terraform plan -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}" -var="sqladmin_username=${{ secrets.SQL_USER }}" -var="sqladmin_password=${{ secrets.SQL_PASS }}" -no-color -out main.tfplan
      
      - name: Aplicar Terraform
        run: |
          cd infra
          terraform apply -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}" -var="sqladmin_username=${{ secrets.SQL_USER }}" -var="sqladmin_password=${{ secrets.SQL_PASS }}" -auto-approve main.tfplan
      
      - name: Setup infracost
        uses: infracost/actions/setup@v3
        with:
            api-key: ${{ secrets.INFRACOST_API_KEY }}
      
      - name: Ejecutar infracost y generar diagrama Mermaid
        run: |
            cd infra
            infracost breakdown --path . --format json --out-file infracost-report.json
            infracost breakdown --path . --format table > infracost-report.md
            infracost generate mermaid --path infracost-report.json > infracost-diagram.mmd
      
      - name: Subir artefactos de infracost
        uses: actions/upload-artifact@v4
        with:
          name: infracost-diagram
          path: infra/infracost-diagram.mmd
      
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      
      - name: Setup inframap
        run: |
            curl -L -o /tmp/inframap.tar.gz "https://github.com/cycloidio/inframap/releases/download/v0.7.0/inframap-linux-amd64.tar.gz"
            tar -xzvf /tmp/inframap.tar.gz -C /tmp
            mv -v /tmp/inframap-linux-amd64 /usr/local/bin/inframap
            chmod +x /usr/local/bin/inframap
      - name: Generar diagrama de infraestructura con inframap
        run: |
            cd infra
            /usr/local/bin/inframap generate main.tf --raw | dot -Tsvg > inframap_azure.svg
      - name: Subir diagrama de infraestructura
        uses: actions/upload-artifact@v4
        with:
          name: inframap_azure.svg
          path: infra/inframap_azure.svg
